<?xml version="1.0"?>
<definitions name="Dummy" targetNamespace="http://foo.com/bar"
             xmlns="http://schemas.xmlsoap.org/wsdl/">
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
            <import namespace="http://foo.com/bar/zoinks" schemaLocation="zoinks.xsd"/>
        </schema>
    </types>

</definitions>
